#!/usr/bin/env python3
"""Generate (or drift-check) rules/ecc/common/agents.md from agents/.

That file is an agent index that loads into every session importing the common
rules. It was upstream's, never regenerated after the cherry-pick, and had drifted
to listing 11 agents - one of which did not exist - while omitting 19 that did.
An index that names a nonexistent agent is worse than no index: the model routes
to it and gets nothing.

  python3 scripts/gen-agent-index.py            rewrite the file from agents/
  python3 scripts/gen-agent-index.py --check    exit 1 if it has drifted

Run --check alongside check-routing.py. Same idea, different table.
"""
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
AGENTS = ROOT / "agents"
INDEX = ROOT / "rules" / "ecc" / "common" / "agents.md"

HEADER = """# Agent Orchestration

> GENERATED by `scripts/gen-agent-index.py` from `agents/`. Do not hand-edit the
> table - regenerate it. `scripts/gen-agent-index.py --check` fails on drift.

## Available Agents

Located in `~/.claude/agents/`:

"""

FOOTER = """
## Immediate Agent Usage

No user prompt needed:
1. Complex feature requests - use **planner**
2. Code just written or modified - use **code-reviewer**
3. Bug fix or new feature - use **tdd-guide**
4. Architectural decision - use **architect** (system design) or **code-architect**
   (a feature blueprint grounded in this codebase)
5. Any diff about to merge - use **regression-hunter**
6. Someone else's pull request - use **pr-intent-verifier**

## Parallel Task Execution

Dispatch independent reviews in a SINGLE message so they run concurrently, then
synthesize. `/review-stack` does this for the review agents.

## Delegation Completion Contract

Applies to every agent at every depth:

1. **Your final message IS the deliverable.** Never end a turn with "waiting for
   background agents" - a spawned task is not a completed task, and ending your
   turn orphans their results.
2. **If you delegate, you own collection.** Wait, integrate, then return.
3. **Decompose only when the work cannot fit in one context.** Depth is an
   outcome, not a plan.
"""


def read_agents():
    rows = []
    for p in sorted(AGENTS.glob("*.md")):
        text = p.read_text(encoding="utf-8")
        m = re.match(r"^---\n(.*?)\n---\n", text, re.S)
        fm = m.group(1) if m else ""
        desc = re.search(r"^description:\s*(.+?)(?=\n[a-z_-]+:|\Z)", fm, re.M | re.S)
        d = " ".join(desc.group(1).split()) if desc else ""
        d = d.strip().strip('"').strip("'")
        # first sentence only - the table is a router, not documentation
        d = re.split(r"(?<=[a-z])\.\s+", d)[0].rstrip(".")
        if len(d) > 110:
            d = d[:107].rsplit(" ", 1)[0] + "..."
        rows.append((p.stem, d))
    return rows


def render(rows):
    out = [HEADER, "| Agent | Purpose |", "|-------|---------|"]
    out += ["| %s | %s |" % (n, d) for n, d in rows]
    return "\n".join(out) + "\n" + FOOTER


def main():
    rows = read_agents()
    if not rows:
        print("no agents found under %s" % AGENTS, file=sys.stderr)
        return 1
    new = render(rows)
    check = "--check" in sys.argv

    old = INDEX.read_text(encoding="utf-8") if INDEX.exists() else ""
    listed = set(re.findall(r"^\| ([a-z][a-z0-9-]+) \|", old, re.M))
    real = {n for n, _ in rows}

    if check:
        ghosts, missing = sorted(listed - real), sorted(real - listed)
        if not ghosts and not missing and old == new:
            print("agent index OK (%d agents)" % len(rows))
            return 0
        if ghosts:
            print("LISTED BUT DOES NOT EXIST: " + ", ".join(ghosts))
        if missing:
            print("EXISTS BUT UNLISTED (%d): %s" % (len(missing), ", ".join(missing)))
        if not ghosts and not missing:
            print("table matches, but surrounding text drifted")
        print("regenerate: python3 scripts/gen-agent-index.py")
        return 1

    INDEX.write_text(new, encoding="utf-8")
    print("wrote %s (%d agents)" % (INDEX.relative_to(ROOT), len(rows)))

    # sync.sh pulls rules/ FROM ~/.claude, so a file generated only into the repo is
    # silently reverted on the next sync. Write both copies. (This bit twice: once
    # here, once on CLAUDE.md.)
    live = pathlib.Path.home() / ".claude" / "rules" / "ecc" / "common" / "agents.md"
    if live.parent.is_dir():
        live.write_text(new, encoding="utf-8")
        print("wrote %s" % live)
    return 0


if __name__ == "__main__":
    sys.exit(main())
